name: Test

on:
  pull_request:
    branches:
      - mesosphere

jobs:
  test:
    name: run-tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install Nix on self-hosted ARC runners
        uses: cachix/install-nix-action@v30
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install devbox
        uses: jetify-com/devbox-install-action@v0.12.0
        with:
          enable-cache: false
          skip-nix-installation: true

      - uses: actions/create-github-app-token@v1
        id: app-token-mesosphere
        with:
          app-id: ${{ secrets.GHA_CHECKOUT_APP_ID }}
          private-key: ${{ secrets.GHA_CHECKOUT_APP_PRIVATE_KEY }}
          owner: mesosphere

      - run: git config --global url."https://oauth2:${{ steps.app-token-mesosphere.outputs.token }}@github.com/mesosphere/".insteadOf "https://github.com/mesosphere/"

      - name: Granting private modules access
        run: |
          git config --global url."https://${{ secrets.MESOSPHERECI_USER_TOKEN }}:x-oauth-basic@github.com/".insteadOf "https://github.com/"

      - run: devbox run -- make test
